# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openemail < Formula
  desc "Command-line client for the OpenEmail platform"
  homepage "https://github.com/Open-Email/cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.2/openemail_0.2.2_darwin_amd64.tar.gz"
      sha256 "81ab8e449103ff892914d034c81425f7bc8cb6ae53ea12cf73fd9f147a46cdd4"

      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.2/openemail_0.2.2_darwin_arm64.tar.gz"
      sha256 "1cf245534eacd8ef28d0421e5d452097f110923f8e9a08aee7efa943e3eb13e2"

      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.2/openemail_0.2.2_linux_amd64.tar.gz"
      sha256 "9747510692715401d3215287d88635b8b83b8b18e6bd7410e05b3e6f033b34c7"
      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.2/openemail_0.2.2_linux_arm64.tar.gz"
      sha256 "5d981f22a991d1e4c2f6d7df76bb06d9855d06931e89157de119cd7fcaf11296"
      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
  end

  test do
    system "#{bin}/openemail", "version"
  end
end
