# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openemail < Formula
  desc "Command-line client for the OpenEmail platform"
  homepage "https://github.com/Open-Email/cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.1/openemail_0.2.1_darwin_amd64.tar.gz"
      sha256 "b9c6208503a1f434824c083ef0b59f7b095507c40031b2313dcfa48144fab803"

      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.1/openemail_0.2.1_darwin_arm64.tar.gz"
      sha256 "0e1b54a750e848af7aa9d3e9468c31e671f5a8a37a27078cf40ea054501f6e32"

      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.1/openemail_0.2.1_linux_amd64.tar.gz"
      sha256 "10529e16267d6a6f9253dce9ca1b2d764f2c6fc2c1d1b6bad30e2f6e7f5ccf5a"
      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Open-Email/cli/releases/download/v0.2.1/openemail_0.2.1_linux_arm64.tar.gz"
      sha256 "543067c05019780254ba54942a349e40f4a2a975057e72b0c341d12e17c9f536"
      define_method(:install) do
        bin.install "openemail"
        bash_completion.install "completions/openemail.bash" => "openemail"
        zsh_completion.install "completions/openemail.zsh" => "_openemail"
        fish_completion.install "completions/openemail.fish"
      end
    end
  end

  test do
    system "#{bin}/openemail", "version"
  end
end
